### PR TITLE
Hidden OU: Adding the moves to the Pokemon

### PR DESCRIPTION
**Pull request by Langur88**

### CODE REVIEW

**Comment by xfix** [comment]
Those are Mega Shrine moves, so they shouldn't be `L100`, but rather `L1` or `M` (learnable at any level, without any conditions).

**Comment by Joimer** [comment]
@Langur88 can you fix what @xfix mentioned?

**Comment by RhythmsAreFromVibrations** [comment]
HI I'm Langur88, and yeah I'll do that

**Comment by Langur88** [comment]
Okay, I added them.

**Pull request merged**
