### PR TITLE
Proposed change to TI

### PR DESCRIPTION
**Pull request by cadaeic**
@TheImmortal I felt that your set is way too similar to TFC's. Since you have Steam Eruption to burn everyone already, maybe you can consider this specially defensive set with ~~Growth~~ Work Up? (boosted DTail spam!)

### CODE REVIEW

**Comment by TheImmortal** [comment]
Joim already made me change my (broken) shit twice. I'm not changing this. Also, it isn't similar at all apart from QD.

**Comment by cadaeic** [comment]
Well, it's the same mon, that's already too similar imo. My main problem is there are too many QDers out there in the meta. 
Too bad you guys decided not to keep the Hoopa-u which looked cool >.<

**Comment by TheImmortal** [comment]
I wouldn't mind changing to Shell Smash IF my custom removed stat drops as well :^) @Joimer what do you say, is that broken

**Comment by cadaeic** [comment]
Maybe a weaker STAB than Steam Eruption? Shell Smash does make a whole lot of sense on Blastoise. I wonder why it isn't common in the seasonal compared to QD\Tail Glow.

**Comment by Joimer** [comment]
@TheImmortal probably broken but go ahead let's try it we have whole saturday to fix the meta

**Comment by TheImmortal** [comment]
**praise** Joim

**Pull request closed without merging**
